from actions.app_actions import open_project_folder, open_terminal, open_vscode
from actions.git_actions import (
    git_branch,
    git_pull,
    git_status,
)
from actions.conda_actions import (
    list_conda_envs,
)
from actions.system_actions import (
    open_logs_file,
    open_task_manager,
)
from actions.work_actions import (
    open_codex,
    open_comet_browser,
    open_github,
    open_jira_tickets,
    open_openprj,
    open_ssms_22,
    open_vs_insiders,
)

ACTIONS = [
    {
        "label": "Open VS Code",
        "description": "Launch the code editor",
        "category": "Development",
        "handler": open_vscode,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open PowerShell",
        "description": "Launch a PowerShell terminal",
        "category": "Development",
        "handler": open_terminal,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open Project Folder",
        "description": "Open your main project directory",
        "category": "Development",
        "handler": open_project_folder,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open Logs File",
        "description": "Open application logs directory",
        "category": "System",
        "handler": open_logs_file,
        "style": "success",
        "type": "launch",
    },
    {
        "label": "Open Task Manager",
        "description": "Inspect running processes",
        "category": "System",
        "handler": open_task_manager,
        "style": "success",
        "type": "launch",
    },
    {
        "label": "Open VS Code Insiders",
        "description": "Launch Visual Studio Code Insiders",
        "category": "Development",
        "handler": open_vs_insiders,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open SSMS 22",
        "description": "Launch SQL Server Management Studio 22",
        "category": "Database",
        "handler": open_ssms_22,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Open Jira Tickets",
        "description": "Open Jira tickets board in browser",
        "category": "Work",
        "handler": open_jira_tickets,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Codex Copilot",
        "description": "Open Codex in browser",
        "category": "Development",
        "handler": open_codex,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Git Status",
        "description": "Show status for selected repository",
        "category": "Git",
        "handler": git_status,
        "style": "warning",
        "type": "task",
    },
    {
        "label": "Git Branch",
        "description": "Show current branch for selected repository",
        "category": "Git",
        "handler": git_branch,
        "style": "warning",
        "type": "task",
    },
    {
        "label": "Git Pull",
        "description": "Pull latest changes for selected repository",
        "category": "Git",
        "handler": git_pull,
        "style": "danger",
        "type": "task",
    },
    {
        "label": "Git Hub",
        "description": "Open Organazation GitHub",
        "category": "Git",
        "handler": open_github,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "OpenProject",
        "description": "Start OpenProject",
        "category": "Work",
        "handler": open_openprj,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Launch Comet",
        "description": "Start a new Comet Browser",
        "category": "Work",
        "handler": open_comet_browser,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "List Conda Envs",
        "description": "Show available Conda environments",
        "category": "Development",
        "handler": list_conda_envs,
        "style": "info",
        "type": "task",
    },
]
