from actions.app_actions import (
    open_ai_dept,
    open_project_folder,
    open_terminal,
    open_vscode,
)
from actions.conda_actions import (
    export_current_env,
    list_conda_envs,
)
from actions.docker_actions import (
    show_docker_containers,
)
from actions.git_actions import (
    git_branch,
    git_pull,
    git_status,
)
from actions.quality_actions import open_desktop_index, open_downloads
from actions.script_actions import (
    open_repo_terminal_with_env,
    run_python_main,
    run_streamlit_app,
    run_uvicorn_app,
)
from actions.system_actions import (
    open_logs_file,
    open_task_manager,
)
from actions.work_actions import (
    open_codex,
    open_comet_browser,
    open_dbdiagram,
    open_github,
    open_jira_tickets,
    open_openprj,
    open_ssms_22,
    open_vs_insiders,
)

ACTIONS = [
    {
        "label": "Open VS Code",
        "description": "Launch the code editor",
        "category": "Development",
        "handler": open_vscode,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open PowerShell",
        "description": "Launch a PowerShell terminal",
        "category": "Development",
        "handler": open_terminal,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open Project Folder",
        "description": "Open your main project directory",
        "category": "Development",
        "handler": open_project_folder,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open AI Department",
        "description": "Open your main project directory",
        "category": "Work",
        "handler": open_ai_dept,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Open Logs File",
        "description": "Open application logs directory",
        "category": "System",
        "handler": open_logs_file,
        "style": "success",
        "type": "launch",
    },
    {
        "label": "Open Task Manager",
        "description": "Inspect running processes",
        "category": "System",
        "handler": open_task_manager,
        "style": "success",
        "type": "launch",
    },
    {
        "label": "Docker Containers",
        "description": "Show running Docker containers",
        "category": "System",
        "handler": show_docker_containers,
        "style": "info",
        "type": "task",
    },
    {
        "label": "Open VS Code Insiders",
        "description": "Launch Visual Studio Code Insiders",
        "category": "Development",
        "handler": open_vs_insiders,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "Open SSMS 22",
        "description": "Launch SQL Server Management Studio 22",
        "category": "Database",
        "handler": open_ssms_22,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Open Jira Tickets",
        "description": "Open Jira tickets board in browser",
        "category": "Work",
        "handler": open_jira_tickets,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Codex Copilot",
        "description": "Open Codex in browser",
        "category": "Development",
        "handler": open_codex,
        "style": "primary",
        "type": "launch",
    },
    {
        "label": "DBdiagram",
        "description": "Open DBdiagram in browser",
        "category": "Database",
        "handler": open_dbdiagram,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Git Status",
        "description": "Show status for selected repository",
        "category": "Git",
        "handler": git_status,
        "style": "warning",
        "type": "task",
    },
    {
        "label": "Git Branch",
        "description": "Show current branch for selected repository",
        "category": "Git",
        "handler": git_branch,
        "style": "warning",
        "type": "task",
    },
    {
        "label": "Git Pull",
        "description": "Pull latest changes for selected repository",
        "category": "Git",
        "handler": git_pull,
        "style": "danger",
        "type": "task",
        "confirm": True,
        "confirm_message": "Pull latest changes for the selected repository?",
    },
    {
        "label": "Repo Terminal",
        "description": "Open terminal in selected repo with selected Conda env",
        "category": "Git",
        "handler": open_repo_terminal_with_env,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Git Hub",
        "description": "Open Organazation GitHub",
        "category": "Git",
        "handler": open_github,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "OpenProject",
        "description": "Start OpenProject",
        "category": "Work",
        "handler": open_openprj,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "Launch Comet",
        "description": "Start a new Comet Browser",
        "category": "Work",
        "handler": open_comet_browser,
        "style": "info",
        "type": "launch",
    },
    {
        "label": "List Conda Envs",
        "description": "Show available Conda environments",
        "category": "Conda",
        "handler": list_conda_envs,
        "style": "info",
        "type": "task",
    },
    {
        "label": "Export Conda Env",
        "description": "Export current environment to environment.yml",
        "category": "Conda",
        "handler": export_current_env,
        "style": "warning",
        "type": "task",
        "confirm": True,
        "confirm_message": "Export current Conda environment to environment.yml?",
    },
    {
        "label": "Open Downloads",
        "description": "Open Windows Downloads folder",
        "category": "Quality of Life",
        "handler": open_downloads,
        "style": "secondary",
        "type": "launch",
    },
    {
        "label": "Open Desktop Index",
        "description": "Open personal desktop cleanup folder",
        "category": "Quality of Life",
        "handler": open_desktop_index,
        "style": "secondary",
        "type": "launch",
    },
    {
        "label": "Run Streamlit",
        "description": "Run streamlit app.py in selected repo",
        "category": "Project Launcher",
        "handler": run_streamlit_app,
        "style": "success",
        "type": "launch",
    },
    {
        "label": "Run Uvicorn",
        "description": "Run FastAPI app.main:app in selected repo",
        "category": "Project Launcher",
        "handler": run_uvicorn_app,
        "style": "success",
        "type": "launch",
    },
    {
        "label": "Run Python Main",
        "description": "Run python main.py in selected repo",
        "category": "Project Launcher",
        "handler": run_python_main,
        "style": "success",
        "type": "launch",
    },
]
